#!/bin/sh

# Read the version from the file
OPENFIRE_VERSION=$(cat openfire_version.txt | sed 's/\./_/g')

# Build the Docker image with the build argument
docker build --build-arg OPENFIRE_VERSION=$OPENFIRE_VERSION -t $IMAGE_NAME:$OPENFIRE_VERSION -t $IMAGE_NAME:latest .