#!/bin/sh

# Read the version from the file
OPENFIRE_VERSION=$(cat openfire_version.txt)

# Build the Docker image with the build argument
docker build --build-arg OPENFIRE_VERSION=$OPENFIRE_VERSION -t armyguy255a/openfire:$OPENFIRE_VERSION .